objects/Candidate__c.object
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>filter__c</fullName>
        <formula>if(DATETIMEVALUE(CreatedDate)&lt;= DATETIMEVALUE(Recruitment_Campaign__r.Deadline__c) , TRUE , FALSE)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>filter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Seniority__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Seniority</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Speciality__c</fullName>
        <label>Speciality</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>University__c</fullName>
        <label>University</label>
        <length>120</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_diploma__c</fullName>
        <label>Type of diploma</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Master</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Education_levelNew__c</fullName>
        <label>Education level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bac</fullName>
                </value>
                <value>
                    <fullName>Bac+3</fullName>
                </value>
                <value>
                    <fullName>Bac+5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Days_after_deadline__c</fullName>
        <formula>DATETIMEVALUE(CreatedDate) - DATETIMEVALUE(Recruitment_Campaign__r.Deadline__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Days after deadline</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recruitment_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recruitment Campaign</label>
        <referenceTo>Recruitment_Campaign2__c</referenceTo>
        <relationshipLabel>Candidates</relationshipLabel>
        <relationshipName>Candidates</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Recruitment_Campaign2__c.object
<CustomObject>
    <label>Recruitment Campaign</label>
    <nameField>
        <label>Recruitment Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recruitment Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Deadline__c</fullName>
        <label>Deadline</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Seniority__c</fullName>
        <label>Seniority</label>
        <length>80</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/Recruitment_Campaign__c.object
<CustomObject>
    <label>Recruitment CampaignArchived</label>
    <nameField>
        <label>Recruitment Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recruitment Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Deadline__c</fullName>
        <label>Deadline</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Seniority__c</fullName>
        <label>Seniority</label>
        <length>80</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/comboboxWithDataTableClass.cls
public class comboboxWithDataTableClass {
    @AuraEnabled
       public static List<Recruitment_Campaign2__c> getRCForCombobox(){
           List<Recruitment_Campaign2__c> rcList = [Select Id,Name,Deadline__c from Recruitment_Campaign2__c];
           return rcList;
       }
    @AuraEnabled
       public static List<Candidate__c> getAllCandidates(){
           List<Candidate__c> candidateList = [Select Id,Name,First_Name__c,Email__c,Recruitment_Campaign__c,Type_of_diploma__c,Speciality__c,University__c,Seniority__c From Candidate__c];
           return candidateList;
       }
      @AuraEnabled
       public static List<Candidate__c> getCandidates(String selectedRcID,Integer Seniority,List<String> type,List<String> level){
           
             List<Candidate__c> candidateList = [Select Id,Name,First_Name__c,Email__c,Recruitment_Campaign__c,Days_after_deadline__c,Type_of_diploma__c,Speciality__c,University__c,Seniority__c,Education_levelNew__c
                                               From Candidate__c
                                               WHERE Recruitment_Campaign__c = :selectedRcID
                                               AND filter__c = true
                                               AND Education_levelNew__c IN :level
                                               AND Type_of_diploma__c IN :type
                                               AND Seniority__c = :Seniority
                                               ];

           return candidateList;
       }

    @AuraEnabled
       public static List<Candidate__c> getLateCandidates(String selectedRcID,Integer Seniority,List<String> type,List<String> level){
            List<Candidate__c> candidateList = [Select Id,Name,First_Name__c,Email__c,Recruitment_Campaign__c,Days_after_deadline__c,Type_of_diploma__c,Speciality__c,University__c,Seniority__c,Education_levelNew__c
                                               From Candidate__c
                                               WHERE Recruitment_Campaign__c = :selectedRcID
                                               AND filter__c = false
                                               AND Education_levelNew__c IN :level
                                               AND Type_of_diploma__c IN :type
                                               AND Seniority__c = :Seniority
                                               ];
           return candidateList;
       }
    
  
   }